#server:
#  port: 8080
#  address: 192.168.1.43
#  
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect          
#
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/lemonade
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
#
  profiles:
    active: dev